### PR TITLE
Fixed typo in goals-signals-metrics.md

### PR DESCRIPTION
**Pull request by Jmaur**
Fixed typo, replaced signals with metrics.

### CODE REVIEW

**Comment by mkanat** [comment]
Ah, no, not a typo, just an unclear sentence structure. I did mean like, if you look at the signals, you'll see that some of these metrics map back to the signals.

**Comment by Jmaur** [comment]
Yeah that's what I understood but it references signals mapping to signals which I thought was really metrics mapping to signals.

**Comment by mkanat** [comment]
Yeah, the sentence is just confusing. I'll send you a PR that clarifies it and you can let me know if it's better.

**Comment by mkanat** [comment]
For some reason GH won't let me assign you as the reviewer of the PR, but it's here: https://github.com/linkedin/dph-framework/pull/16.

**Pull request closed without merging**
